DRAFT: feat: Scaida rebranding
thoughtswinsystems/OHIFViewer pull request #2
Opened 2024-04-04 10:15 UTC by chetanppatil

- added scaida svg logo in assets
- added two css class in tailwind.css according to figma design
- on pages set white theme and new added css class as property to set proper color
- using whitelabling functionality, updated scaida logo

### Context

### Changes & Results

### Testing

### Checklist

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2024-04-04 10:16 UTC, chetanppatil commented
Current State Looks Like:

<img width="1786" alt="image" src="https://github.com/thoughtswinsystems/OHIFViewer/assets/31822501/a44712f6-b62b-417a-bc91-22038180e7c1">

2024-04-19 05:30 UTC, VarshaMLHealth commented on extensions/default/src/ViewerLayout/index.tsx
> +    console.log('Pratik Entry', entry);
Can you please remove this console.log

2024-04-19 05:31 UTC, VarshaMLHealth commented on platform/app/public/config/default.js
> +    // {
Remove unwanted code, instead of commenting it

2024-04-19 05:32 UTC, VarshaMLHealth requested changes
added review comments Please check
also you forgot to pull changes from The PR i raised. Please pull those changes too.

2024-06-05 19:23 UTC, rajangoswamiTWS commented
@Pratik-TWS, @VarshaMLHealth 
What is the status of this PR? Why is this not committed yet?

2024-07-04 10:58 UTC, closed without merging